### PR TITLE
Oauth2.0.1   ashaar

### PR DESCRIPTION
**Pull request by jixi0901**
*Tried maven build by using the source code uploaded 2 days ago. Not successful.
*Sat with Raji to go through the codes
*Following are initial findings by Raji:
1. No documentation provided for deploying or use case.
2. A local Mysql DB properties file is at code base.
3. No DB changes to existing OPENHMIS2 Schema.
4. Spring frame work is used to implement OAUTH server side component.

### CODE REVIEW

**Comment by ashaar364** [comment]
The code I have shared is the first version, I am working on it and I will update you by the end of this week or early next week. I will write a document about the deployment,
I have created a database as well, will share with you it as well.
We will be making the changing in the existing Openhims2 schema once things are working.
Yes Spring framework is used in the implementing the Oauth Server, I have already wrote a document about the design where I have mentioned that I will be using the Spring Framework.

This code base or branch is using maven and my previous  OpenHMIS branch is not using Spring, I will merge once the Oauth Server is finalize. I suggest we shouldn't merge both the branches at this time.

**Comment by steveconners** [comment]
Ashaar,

Do you have an intent as to how you would like the directory structure of
this repository to look when you are done? (the API with 3 different OAuth
client options and the OAuth server) This repository is already a little
snarled.

Steve

**Comment by ashaar364** [comment]
Steve:
I would like to keep the code for the 3-API at one place and code for the Oauth Server separate. Not only the code we have database, documentation and build system. We need to organize all of them as well. I will back to this early next week.

Ashaar

**Comment by slifty** [comment]
@ashaar364 am I correct in understanding that this pull request is now stale and should be closed off along with the `Oauth2.0.1---Ashaar` branch?

**Comment by ashaar364** [comment]
@slifty Yes that is right. it should be close now.

**Pull request closed without merging**
